# These are supported funding model platforms

github: [beardedtek-com]
custom: ['https://www.paypal.com/donate/?hosted_button_id=H66VP9K2BNFGG','https://getalby.com/p/beardedtek','https://beardedtek.org','https://tallycoin.app/@beardedtek/beardedtek-donations-waqwip/']
