# These are supported funding model platforms

github: [beardedtek-com]
custom: ['https://getalby.com/p/beardedtek','https://beardedtek.org','https://tallycoin.app/@beardedtek/beardedtek-donations-waqwip/']
