---
kind: pipeline
type: docker
name: test
trigger:
  branch:
    - drone-test
  event:
    - push

steps:
- name: dev-docker-test
  image: docker:dind
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - sleep 10000