---
kind: pipeline
type: docker
name: test
trigger:
  branch:
    - drone-test
  event:
    - push

steps:
- name: apidb-drone
  image: postgres
  detach: true
  environment:
    POSTGRES_USER:
      from_secret: DATABASSE_DB_USER
    POSTGRES_PASSWORD:
      from_secret: DATABASE_DB_PASS
    POSTGRES_DB:
      from_secret: DATABASE_DB

- name: apitest-drone
  image: python:3.11.5-bullseye
  environment:
    DATABASE_DB:
      from_secret: DATABASE_DB
    DATABASE_DB_HOST: apidb-drone
    DATABASE_DB_USER:
      from_secret: DATABASE_DB_USER
    DATABASE_DB_PASS:
      from_secret: DATABASE_DB_PASS
    BLOGINDEX_DEBUG:
      from_secret: BLOGINDEX_DEBUG
    BLOGINDEX_LOG_LEVEL:
      from_secret: BLOGINDEX_LOG_LEVEL
    AUTH0_DOMAIN:
      from_secret: AUTH0_DOMAIN
    AUTH0_API_AUDIENCE:
      from_secret: AUTH0_API_AUDIENCE
    AUTH0_ISSUER:
      from_secret: AUTH0_ISSUER
    AUTH0_ALGORITHMS:
      from_secret: AUTH0_ALGORITHMS
    AUTH0_CLIENT_ID:
      from_secret: AUTH0_CLIENT_ID
    AUTH0_CLIENT_SECRET:
      from_secret: AUTH0_CLIENT_SECRET
  
  commands:
  - export RESULT_LOCATION="/result/$(date +%Y-%d-%m_%H-%M-%S)"
  - Running Tests
  - /drone/src/dev/drone/test.sh > ${RESULT_LOCATION}.txt
  - /drone/src/dev/drone/post_test.sh