kind: pipeline
type: ssh
name: apitest_ssh

server:
  host: 192.168.10.2
  user: beardedtek
  ssh_key:
    from_secret: ssh_key

steps:
  - name: pytest
    commands:
      - mkdir -p /drone/pytest
      - cd /drone/pytest
      - rm -rf blogindex
      - git clone https://github.com/blogindex/blogindex.xyz.git blogindex
      - cd blogindex/dev/docker/test
      - docker compose down
      - docker compose up -d
      - docker compose logs -f > /results/$(date +%Y-%m-%d_%H-%M-%S)-stdout.txt
