version: "3"
services:
  postgres:
    container_name: blogindex-postgres
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=local
    volumes:
      - ./scripts/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
