hobbies = [
    "Reading",
    "Hiking",
    "Cooking",
    "Painting",
    "Photography",
    "Gardening",
    "Swimming",
    "Playing Chess",
    "Singing",
    "Dancing",
    "Traveling",
    "Writing",
    "Mountain Biking",
    "Bird Watching",
    "Yoga",
    "Fishing",
    "Camping",
    "Knitting",
    "Rock Climbing",
    "Surfing",
    "Meditation",
    "Golfing",
    "Scuba Diving",
    "Volunteering",
]