---
version: '3'

services:

  api:
    container_name: api
    build: .
    image: blogindex/api:main
    volumes:
      - /path/to/codebase:/blogindex/ # OPTIONAL
    depends_on:
      - apidb
    environment:
      - DATABASE_DB=${DATABASE_DB:-blogindex}
      - DATABASE_DB_HOST=${DATABASE_DB_HOST:-db}
      - DATABASE_DB_USER=${DATABASE_DB_USER:-blogindex}
      - DATABASE_DB_PASS=${DATABASE_DB_PASS:-blogindex}
      - BLOGINDEX_DEBUG=${BLOGINDEX_DEBUG:-True}
      - BLOGINDEX_LOG_LEVEL=${BLOGINDEX_LOG_LEVEL:-DEBUG}
      # These variables can be obtained by messaging @BeardedTek:matrix.org
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
      - AUTH0_ISSUER=${AUTH0_ISSUER}
      - AUTH0_ALGORITHMS=${AUTH0_ALGORITHMS}
  
  apidb:
    container_name: apidb
    hostname: ${DATABASE_DB_HOST:-db}
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_DB_USER:-blogindex}
      - POSTGRES_PASSWORD=${DATABASE_DB_PASS:-blogindex}
      - POSTGRES_DB=${DATABASE_DB:-blogindex}
  