#!/usr/bin/env bash
rm -rf /results/finished
FINISHED=99
until [ "${FINISHED}" = "0" ]; do
    if [ -f "/results/finished" ]
        FINISHED=0
    fi
    sleep 10
    echo "$(date -I)  ::: loop hasn't seen /results/finished yet."
done
sleep 60 
pkill -f test